### ISSUE TITLE
TypeError: unhashable type: 'Pmf' (thinkbayes.py)

### ISSUE THREAD

**Issue by ssrrapper** [AllenDowney/ThinkBayes#19]
When trying to run code from hockey.py, I get:

Traceback (most recent call last):

  File "<ipython-input-17-72ea29c7b0d9>", line 1, in <module>
    runfile('C:/Users/ssrra/.spyder-py3/temp.py', wdir='C:/Users/ssrra/.spyder-py3')

  File "C:\Users\ssrra\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\ssrra\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ssrra/.spyder-py3/temp.py", line 541, in <module>
    main()

  File "C:/Users/ssrra/.spyder-py3/temp.py", line 435, in main
    goal_dist1 = MakeGoalPmf(suite1)

  File "C:/Users/ssrra/.spyder-py3/temp.py", line 127, in MakeGoalPmf
    metapmf.Set(pmf, prob)

  File "C:\Users\ssrra\.spyder-py3\thinkbayes.py", line 589, in Set
    self.d[x] = y

TypeError: unhashable type: 'Pmf'

**Comment by AllenDowney** [comment]
I will check it out.  Thanks for letting me know.
